config/routes.rb
Rails.application.routes.draw do
  resources :estudiantes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: %i[ show edit update destroy ]

  # GET /estudiantes or /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1 or /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes or /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to estudiante_url(@estudiante), notice: "estudiante...." }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1 or /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to estudiante_url(@estudiante), notice: "Datos actualizados..." }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1 or /estudiantes/1.json
  def destroy
    @estudiante.destroy

    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: "Estudiante eliminado ." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.require(:estudiante).permit(:nombre, :cedula, :apellido, :edad, :curso, :nota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_estudiante.html.erb
<div id="<%= dom_id estudiante %>">
  <p>
    <strong>Nombre:</strong>
    <%= estudiante.nombre %>
  </p>

  <p>
    <strong>Cedula:</strong>
    <%= estudiante.cedula %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= estudiante.apellido %>
  </p>

  <p>
    <strong>Edad:</strong>
    <%= estudiante.edad %>
  </p>

  <p>
    <strong>Curso:</strong>
    <%= estudiante.curso %>
  </p>

  <p>
    <strong>Nota:</strong>
    <%= estudiante.nota %>
  </p>


</div>

app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante) do |form| %>
  <% if estudiante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
        <% estudiante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "form-group mt-3">
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre, class:'form-control form-control-lg'  %>
  </div>

  <div class= "form-group mt-3">
    <%= form.label :cedula, style: "display: block" %>
    <%= form.text_field :cedula, class:'form-control form-control-lg'  %>
  </div>


  <div class= "form-group mt-3">
    <%= form.label :apellido, style: "display: block" %>
    <%= form.text_field :apellido, class:'form-control form-control-lg'  %>
  </div>

  <div class= "form-group mt-3">
    <%= form.label :edad, style: "display: block" %>
    <%= form.number_field :edad, class:'form-control form-control-lg' %>
  </div>

  <div class= "form-group mt-3">
    <%= form.label :curso, style: "display: block" %>
    <%= form.text_field :curso, class:'form-control form-control-lg'  %>
  </div>

  <div class= "form-group mt-3">
    <%= form.label :nota, style: "display: block" %>
    <%= form.text_field :nota, class:'form-control form-control-lg'  %>
  </div>

    <div class= "form-group mt-3">
   <%= form.submit 'Registrar', :class => 'btn btn-outline-primary btn-lg' %>
   <%= link_to " Regresar a estudiantes", estudiantes_path, class: "btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
  <h1 class="card-title">Editar estudiante</h1>
  </div>
     <div class="card-body">
        <%= render "form", estudiante: @estudiante %>
    </div>
  </div>
</div>

app/views/estudiantes/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="col-log-8 mx-auto" style="background-color:#ccc">
  <h1>Estudiantes</h1>
  <%= link_to "Nuevo Estudiante", new_estudiante_path, class:"btn btn-success btn-lg mb-3" %>
  <div id="estudiantes">
    <% @estudiantes.each do |estudiante| %>
     <div class="card shadow mb-3">
      <div class="card-body ">
         <%= render estudiante %>
       <p>
      <%= link_to "Ver este estudiante", estudiante, class:"btn btn-primary" %>
      </p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/estudiantes/new.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
  <h1 class="card-title">Nuevo estudiante</h1>
  </div>
     <div class="card-body">
        <%= render "form", estudiante: @estudiante %>
    </div>
  </div>
</div>

app/views/estudiantes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="col-lg-8">
  <div class="card shadow">
    <div class="card-body">
      <%= render @estudiante %>
     </div>
   </div>
 <div class= "mt-3">
  <%= link_to "Editar estudiante", edit_estudiante_path(@estudiante), class:"btn btn-warning" %> |
  <%= link_to "Regresar a estudiantes", estudiantes_path, class: "btn btn-outline-primary" %>
<div class= "mt-3">
  <%= button_to "Eliminar estudiante", @estudiante, method: :delete, class: "btn btn-danger" %>

   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escuela</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
            <%= yield %>
  </div>
    </div>

  </body>
</html>